In [1]:
import pandas as pd
import os

In [13]:
group_id = 'partek_myod_young'
directory = 'partek_intermediate_files/'
classification = 'MyoD1 MuSCs'

In [14]:
raw_file = '../raw_data/' + group_id + '.txt'
raw_data = pd.read_csv(raw_file,sep='\t')

In [15]:
filtered_data = raw_data[raw_data['Classifications'] == classification]
cell_id_raw_name_map = filtered_data[['Name']]
cell_id_raw_name_map = cell_id_raw_name_map.rename(columns={'Name': 'raw_id'})

In [16]:
long_filtered_data = filtered_data.transpose()
cell_expression_array = long_filtered_data[8:]

gene_list = cell_expression_array.index.tolist()

In [17]:
cell_expression_array.head()

,120,239,334,481,1281,1303,1640,1844,1935,2083,...,3157,3302,3840,4144,4205,4504,4541,4559,4857,4940
0610005C13Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0610009B22Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0610009O20Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
0610010F05Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
0610010K14Rik,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0